# Generated by Django 4.1.2 on 2022-11-02 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_extInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_contact', models.CharField(default='', max_length=10, null=True)),
                ('emp_job_title', models.CharField(default='', max_length=10, null=True)),
                ('emp_no_of_employees', models.CharField(default='', max_length=10, null=True)),
                ('emp_interest', models.CharField(default='', max_length=10, null=True)),
                ('emp_free_text', models.CharField(default='', max_length=10, null=True)),
                ('emp_country', models.CharField(default='', max_length=10, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
